version: '3'
services:
  db:
    image: postgres:13-alpine
    container_name: local-db
    environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=local-db
    networks:
      - local
    ports:
      - "5432:5432"
  app:
    build: "./"
    container_name: graduate-work
    networks:
      - local
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://local-db:5432/local-db
      - spring.datasource.username=user
      - spring.datasource.password=password
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.generate-ddl=true
    depends_on:
      - db
networks:
    local:
      external: true